name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql-client

      - name: Make bash script executable
        run: chmod +x reset_test_db.bash

      - name: Run tests
        env:
          DATABASE: ${{secrets.TEST_DATABASE_ADDRESS}}
          DATABASE_URL: ${{secrets.TEST_DATABASE_ADDRESS}}
          SECRET_KEY: ${{secrets.TEST_SECRET_KEY}}
        run: ./test.bash

      - name: Coverage report
        run: poetry run coverage xml

      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@master

  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Pylint
        run: poetry run pylint --rcfile=.pylintrc --fail-under=9 src

  robot_test:

    runs-on: ubuntu-latest
    needs: test
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Reset test database
        env:
          DATABASE: ${{secrets.TEST_DATABASE_ADDRESS}}
          DATABASE_URL: ${{secrets.TEST_DATABASE_ADDRESS}}
          SECRET_KEY: ${{secrets.TEST_SECRET_KEY}}
        run: ./reset_test_db.bash

      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
